# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  asd1.example.com:
  asd2.example.com:
  

networks:
  byfn:

services:

  asd1.example.com:  
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name:asd1.example.com
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/example.com/orderers/asd1.example.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/example.com/orderers/asd1.example.com/tls/:/var/hyperledger/orderer/tls
        - asd1.example.com:/var/hyperledger/production/orderer
    ports:
    - 7050:7050

  asd2.example.com:  
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name:asd2.example.com
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/example.com/orderers/asd2.example.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/example.com/orderers/asd2.example.com/tls/:/var/hyperledger/orderer/tls
        - asd2.example.com:/var/hyperledger/production/orderer
    ports:
    - 8050:7050

  
